import { NextResponse } from "next/server";
import { SquareClient, SquareEnvironment } from "square";

export async function POST(req: Request) {
    const accessToken = process.env.SQUARE_ACCESS_TOKEN;
    // const environment = SquareEnvironment.Sandbox; 
    // Use production if not sandbox env var, or clearer logic:
    const environment = process.env.SQUARE_ENVIRONMENT === 'production'
        ? SquareEnvironment.Production
        : SquareEnvironment.Sandbox;

    const client = new SquareClient({
        token: accessToken || "",
        environment: environment,
    });

    try {
        const { sourceId, amount, merchantId, cardholderName, customerEmail } = await req.json();

        // 1. Process the payment using the token (sourceId) generated by the frontend
        const response = await client.payments.create({
            sourceId: sourceId,
            idempotencyKey: crypto.randomUUID(),
            amountMoney: {
                amount: BigInt(Math.round(Number(amount) * 100)),
                currency: "USD",
            },
            buyerEmailAddress: customerEmail,
            note: `Merchant: ${merchantId}${cardholderName ? ` | Customer: ${cardholderName}` : ''}`,
        });

        // 2. Return success
        return NextResponse.json({
            success: true,
            paymentId: response.payment?.id
        });

    } catch (error: any) {
        console.error("Square Payment Error Details:", error);
        const detail = error.errors ? error.errors[0]?.detail : error.message;
        return NextResponse.json({
            error: detail || "Payment processing failed"
        }, { status: 500 });
    }
}
